services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_db
    ports:
      - "5435:5432"
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://user:password@db:5432/crud_db
